spring.application.name=organizapp-backend
spring.profiles.active=dev

# JWT
jwt.secret=c2VjcmV0S2V5Rm9yR29yYWlnYXBwMjAyN0F1dGhlbnRpY2F0aW9uS2V5MTIzNDU
jwt.expiration-ms=86400000

# CORS — orígenes permitidos (sobreescribible con CORS_ALLOWED_ORIGINS en K8s)
cors.allowed-origins=http://localhost:4200,https://grupo14.inphotech.co
