spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

jwt.secret=${JWT_SECRET:clave-desarrollo-no-usar-en-produccion-debe-ser-larga-minimo-64-caracteres-aqui}
jwt.expiration=${JWT_EXPIRATION:86400000}

# CORS — sobreescribible con CORS_ALLOWED_ORIGINS en K8s
cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:4200,https://grupo14.inphotech.co}
